---
- name: InitBook
  hosts: all
  roles:
    - { role: init, tags: [always] }  # <- Required initial tasks

- name: BaseBook
  hosts: all
  roles:
    - role: bash
      tags: [bash]
      when: bash_managed | default(false)

    - role: cli-downloaders
      tags: [cli-downloaders]
      when: cli_downloaders_managed | default(false)

    - role: docker
      tags: [docker]
      when: docker_managed | default(false)

    - role: editors
      tags: [editors]
      when: editors_managed | default(false)

    - role: envar
      tags: [envar]
      when: envar_managed | default(false)

    - role: ps1-git
      tags: [ps1-git]
      when: ps1_git_managed | default(false)

    - role: upgrade
      tags: [upgrade, upgradable, never]

- name: ServiceBook
  hosts: all
  roles:
    - role: nginx-proxy
      tags: [nginx-proxy, upgradable]
      when: nginx_proxy_managed | default(false)

    - role: nginx-proxy-manager
      tags: [nginx-proxy-manager, upgradable]
      when: nginx_proxy_manager_managed | default(false)
