---
- name: Load tasks
  ansible.builtin.include_tasks:
    file: tasks.yaml
  vars:
    editors_packages_todo: "{{
        editors_packages | difference(editors_packages_done | default([]))
      }}"
  when: editors_packages_todo | length > 0
