---
- name: Load tasks
  ansible.builtin.include_tasks:
    file: tasks.yaml
  vars:
    bash_packages_todo: "{{ bash_packages | difference(bash_packages_done | default([])) }}"
  when: bash_packages_todo | length > 0
