---
- name: Epel release
  become: true
  vars:
    key_url: https://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-{{ ansible_distribution_major_version }}
    package: https://dl.fedoraproject.org/pub/epel/epel-release-latest-{{ ansible_distribution_major_version }}.noarch.rpm
  block:
    - name: Install GPG key   # <- https://stackoverflow.com/a/64464040
      ansible.builtin.rpm_key:
        state: present
        key: "{{ key_url }}"

    - name: Install
      ansible.builtin.dnf:
        name: "{{ package }}"
        # disable_gpg_check: true

- name: Mark done
  ansible.builtin.set_fact:
    _epel_release_done: true
