---
- name: Privileged
  become: true
  block:
    - name: Create keyrings directory
      ansible.builtin.file:
        path: "{{ ppa_deps_keyrings_dir }}"
        mode: '0755'
        state: directory

    - name: Install packages
      ansible.builtin.package:
        name:
          - ca-certificates
          - gpg

- name: Mark done
  ansible.builtin.set_fact:
    ppa_deps_done: true
