---
- name: Load tasks
  ansible.builtin.include_tasks:
    file: tasks.yaml
  vars:
    cli_downloaders_packages_todo: "{{
        cli_downloaders_packages | difference(cli_downloaders_packages_done | default([]))
      }}"
  when: cli_downloaders_packages_todo | length > 0
