---
cli_downloaders_all:
  - curl
  - wget

cli_downloaders_packages: "{{ (cli_downloaders_pick | length > 0) \
  | ternary(cli_downloaders_all | intersect(cli_downloaders_pick), cli_downloaders_all) }}"
