---
- name: BaseBook
  hosts: all
  roles:
    - { role: init, tags: [always] }  # <- Required initial tasks

    #
    # Base roles
    #
    - role: cli-downloaders
      tags: [cli-downloaders]
      when: cli_downloaders_managed | default(false)

    - role: docker
      tags: [docker]
      when: docker_managed | default(false)

    - role: editors
      tags: [editors]
      when: editors_managed | default(false)

    - role: upgrade
      tags: [upgrade, upgradable, never]
