---
- name: Create keyrings directory
  ansible.builtin.file:
    path: "{{ ppa_deps_keyrings_dir }}"
    mode: '0755'
    state: directory

- name: Install packages
  ansible.builtin.package:
    name:
      - ca-certificates
      - gpg
  become: true

- name: Mark done
  ansible.builtin.set_fact:
    _ppa_deps_done: true
